import {execFileSync} from 'node:child_process';
import {test,expect} from '@playwright/test';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import JSZip from 'jszip';
test.beforeAll(()=>{execFileSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--local','--config','wrangler.local.jsonc','--command',"DELETE FROM projects WHERE owner='demo'; DELETE FROM throttle;"],{stdio:'pipe',timeout:60000});});
async function login(page:any){await page.goto('/');await page.getByLabel('代號',{exact:true}).fill('demo');await page.getByLabel('密碼',{exact:true}).fill('local-demo-only');await page.getByRole('button',{name:'登入',exact:true}).click();await expect(page.locator('.topbar')).toBeVisible();}
async function create(page:any){if(page.viewportSize().width<=800)await page.getByRole('button',{name:'開啟專案列表'}).click();await page.getByRole('button',{name:'建立新文稿',exact:true}).first().click();await page.getByRole('button',{name:'建立文稿',exact:true}).click();await expect(page.locator('.modal')).toBeHidden();await expect(page.locator('.busy-toast')).toBeHidden();await expect(page.getByLabel('文稿標題')).toBeEnabled();}
test('真正本地後端保存、來源確認、四格式下載與繁中內容',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await login(page);expect((await page.request.get('/')).headers()['content-security-policy']).toContain('default-src');await create(page);await page.getByLabel('文稿標題').fill('本地驗收中文文稿');await page.getByLabel('章節內容').fill('# 測試小節\n\n繁體**重點**與來源 [S1]。\n\n| 名稱 | 結果 |\n| --- | --- |\n| 中文 | 通過 |'+Array.from({length:55},(_,i)=>'\n| 中文資料 '+(i+1)+' | 換頁後仍可閱讀的驗證結果 |').join(''));await page.getByLabel('文稿標題').click();
 await expect(page.getByRole('button',{name:'已存本機',exact:false})).toBeVisible({timeout:15000});
 await page.getByRole('button',{name:'來源資料',exact:false}).click();await page.getByLabel('擷取預覽／貼上文字').fill('自製測試來源：本文件用於繁中排版驗收。');await expect(page.getByRole('button',{name:'確認加入',exact:false})).toBeEnabled();await page.getByRole('button',{name:'確認加入',exact:false}).click();await page.getByRole('button',{name:'關閉',exact:true}).click();
 await expect(page.getByRole('button',{name:'來源資料',exact:false})).toContainText('1');
 const exported:Record<string,Buffer>={}; await page.getByRole('button',{name:'匯出',exact:true}).click();
 for(const format of ['MD','DOCX','PDF','EPUB']){
 const downloadPromise=page.waitForEvent('download',{timeout:60000});await page.getByRole('button',{name:format,exact:true}).click();const download=await downloadPromise;expect(await download.failure()).toBeNull();const path=await download.path();const bytes=await readFile(path!);exported[format]=bytes;expect(bytes.length).toBeGreaterThan(100);
 if(format==='MD')expect(new TextDecoder().decode(bytes)).toContain('繁體**重點**');if(format==='DOCX'){const zip=await JSZip.loadAsync(bytes);expect(await zip.file('word/document.xml')!.async('string')).toContain('繁體');}if(format==='PDF'){expect(new TextDecoder().decode(bytes.subarray(0,4))).toBe('%PDF');await mkdir('.qa',{recursive:true});await writeFile('.qa/pdf-verification.pdf',bytes);}if(format==='EPUB'){const zip=await JSZip.loadAsync(bytes);expect(await zip.file('mimetype')!.async('string')).toBe('application/epub+zip');}
 }
 await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.getByRole('button',{name:'來源資料',exact:false}).click();
 for(const format of ['DOCX','PDF']){await page.locator('input[type=file]').first().setInputFiles({name:'中文回讀.'+format.toLowerCase(),mimeType:format==='PDF'?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:exported[format]});await expect(page.getByLabel('擷取預覽／貼上文字')).toHaveValue(/繁體/,{timeout:30000});}
 await page.getByRole('button',{name:'關閉',exact:true}).click();await page.reload();await expect(page.getByLabel('文稿標題')).toHaveValue('本地驗收中文文稿');await expect(page.getByLabel('章節內容')).toHaveValue(/繁體/);expect(errors).toEqual([]);
});
test('AI大綱與超額UI使用明確模擬回應，不覆寫原稿',async({page})=>{
 await login(page);await create(page);await page.getByRole('button',{name:'來源資料',exact:false}).click();await page.getByLabel('擷取預覽／貼上文字').fill('公開自製來源資料');await page.getByRole('button',{name:'確認加入',exact:false}).click();await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.route('**/api/projects/*/ai',async route=>{const body=route.request().postDataJSON();await route.fulfill({status:body.action==='outline'?200:429,contentType:'application/json',body:JSON.stringify(body.action==='outline'?{text:'{"chapters":[{"title":"測試導讀"},{"title":"測試方法"}]}'}:{error:'免費額度已達限制，原稿已保留'})});});
 await page.getByRole('button',{name:'生成大綱',exact:false}).click();await expect(page.getByLabel('可修改的大綱')).toHaveValue('測試導讀\n測試方法');await page.getByRole('button',{name:'確認套用大綱'}).click();await expect(page.getByLabel('章節名稱')).toHaveValue('測試導讀');await page.getByLabel('章節內容').fill('不可被失敗生成覆寫的原稿');await page.getByLabel('文稿標題').click();await page.getByRole('button',{name:'產生草稿',exact:false}).click();await expect(page.getByRole('alert')).toContainText('免費額度');await expect(page.getByLabel('章節內容')).toHaveValue('不可被失敗生成覆寫的原稿');
});
for(const width of [360,390,768,1440])test('RWD '+width+' 無溢出與中文工作區',async({page})=>{
 await page.setViewportSize({width,height:950});await login(page);await create(page);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 if(width<=800){await page.getByRole('tab',{name:'預覽',exact:true}).click();await expect(page.locator('.preview')).toBeVisible();await page.getByRole('tab',{name:'章節',exact:true}).click();await expect(page.locator('.chapters')).toBeVisible();await page.getByRole('tab',{name:'編輯',exact:true}).click();}
 await page.screenshot({path:'.qa/rwd-'+width+'.png',fullPage:true});
});
test('同帳號第二分頁唯讀、不改掉第一份稿件',async({page,context})=>{await login(page);await create(page);const other=await context.newPage();await other.goto('/');await expect(other.getByRole('alert')).toContainText('唯讀');await expect(other.getByLabel('章節內容')).toBeDisabled();await other.close();});
test('來源檔案先預覽，確認前不加入',async({page})=>{await login(page);await create(page);await page.getByRole('button',{name:'來源資料',exact:false}).click();await page.locator('input[type=file]').first().setInputFiles({name:'繁中來源.txt',mimeType:'text/plain',buffer:Buffer.from('來源中文測試','utf8')});await expect(page.getByLabel('擷取預覽／貼上文字')).toHaveValue('來源中文測試');await expect(page.locator('.source-list details')).toHaveCount(0);await page.getByRole('button',{name:'確認加入',exact:false}).click();await expect(page.locator('.source-list details')).toHaveCount(1);});

test('離線編輯保留，恢復連線自動同步',async({page,context})=>{await login(page);await create(page);await context.setOffline(true);await page.getByLabel('章節內容').fill('離線仍要保留的中文草稿');await page.getByLabel('文稿標題').click();await expect(page.getByRole('button',{name:'待同步',exact:false})).toBeVisible();await expect(page.getByRole('alert')).toContainText(/fetch|連線/i,{timeout:10000});await context.setOffline(false);await expect(page.getByRole('button',{name:'已存本機',exact:false})).toBeVisible({timeout:15000});await page.reload();await expect(page.getByLabel('章節內容')).toHaveValue('離線仍要保留的中文草稿');});
test('另一裝置更新後顯示衝突，兩份文字保留',async({page})=>{await login(page);await create(page);const list=await (await page.request.get('/api/projects',{headers:{'X-Wenxu-Account':'demo'}})).json();const p=list[0];const server={...p,title:'另一裝置的新標題',chapters:p.chapters.map((c:any,i:number)=>i===0?{...c,content:'伺服器中文版本'}:c)};expect((await page.request.put('/api/projects/'+p.id,{data:server,headers:{Origin:new URL(page.url()).origin,'X-Wenxu-Account':'demo'}})).ok()).toBe(true);await page.getByLabel('章節內容').fill('本機中文版本');await page.getByLabel('文稿標題').click();await expect(page.getByRole('heading',{name:'選擇要繼續編輯的版本'})).toBeVisible({timeout:15000});await page.getByRole('button',{name:'繼續使用本機內容'}).click();await expect(page.getByRole('button',{name:'已存本機',exact:false})).toBeVisible({timeout:15000});await expect(page.getByLabel('章節內容')).toHaveValue('本機中文版本');await page.getByRole('button',{name:'版本',exact:true}).click();await expect(page.locator('.revision-list')).toContainText('伺服器中文版本');});

test('登出後回登入頁且稿件不能未登入取得',async({page})=>{await login(page);await page.getByRole('button',{name:'登出',exact:true}).click();await expect(page.getByRole('heading',{name:'開始你的寫作空間'})).toBeVisible();expect((await page.request.get('/api/projects',{headers:{'X-Wenxu-Account':'demo'}})).status()).toBe(401);});
