import {useEffect,useRef,useState} from 'react';
import {Feather,BookOpen,Upload,Download,Check,ArrowRight,FileText,X,CheckCircle2,CircleHelp,Plus,Bold,Heading2,List,Quote,Undo2,History,PencilLine,Sparkles,ClipboardPaste,MessagesSquare,ShieldCheck} from 'lucide-react';
import {extractSource,exportProject} from './documents';
import {splitImportedText,type PreviewChapter} from './preview-text';
import type {Project,Identity} from './types';
import {api,setExpectedAlias} from './api';
import WorkspaceTour,{tourSteps} from './WorkspaceTour';
import {resolveSuggestion,type Suggestion,type SavedVersion} from './suggestion-model';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import './blue-preview.css';
import './wenxu-redesign.css';
const SAMPLE='第一章 計畫背景\n閱讀讓我們認識不同的生活，也讓人與人之間產生連結。本計畫希望透過社區共讀活動，提供居民一個分享故事、交換想法的空間。\n\n活動將以在地生活為主題，邀請不同年齡的居民共同參與。從一本書出發，延伸到自己的經驗，讓閱讀成為日常生活的一部分。\n\n本章為自製介面示範文字。實際執行方式、參與人數與經費，待後續補充。\n第二章 執行方式\n每月安排一場小型共讀，選擇與社區生活相關的文章或書籍。活動由主持人引導討論，保留自由分享的時間。\n\n場地、時程與主持人皆待確認。\n第三章 預期成果\n希望參與者能透過閱讀交流，增加對在地生活的理解。成果指標與評估方式待補充，不預先填入未取得的數據。';
interface Draft{title:string;chapters:PreviewChapter[];sourceName?:string;versions?:SavedVersion[];suggestions?:Suggestion[]}
function draftKey(alias:string){return 'wenxu.blue-preview.v2.'+encodeURIComponent(alias);}
function initial(alias:string):Draft|null{try{const d=JSON.parse(localStorage.getItem(draftKey(alias))||'null');if(d&&typeof d.title==='string'&&Array.isArray(d.chapters)&&d.chapters.length&&d.chapters.every((c:any)=>typeof c.id==='string'&&typeof c.title==='string'&&typeof c.content==='string'))return d;}catch{}return null;}

function Workspace({identity,seed,onLogout}:{identity:Identity;seed:Draft;onLogout:()=>void}){
 const [tab,setTab]=useState('edit'),[chaptersOpen,setChaptersOpen]=useState(false),[assistantOpen,setAssistantOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[tour,setTour]=useState(()=>{try{return localStorage.getItem('wenxu.tour.v3.'+identity.alias)?-1:0;}catch{return 0;}});
 const [doc,setDoc]=useState<Draft>(seed),[chapterId,setChapterId]=useState(''),[prompt,setPrompt]=useState(''),[scope,setScope]=useState('chapter'),[selection,setSelection]=useState<{start:number;end:number;text:string}|null>(null),[status,setStatus]=useState('已存本機'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<Draft[]>([]);
 const [mode,setMode]=useState('edit'),[assistantTab,setAssistantTab]=useState('request'),[manualOpen,setManualOpen]=useState(false),[manualText,setManualText]=useState(''),[compareId,setCompareId]=useState('');
 const editor=useRef<HTMLTextAreaElement>(null),beforeEdit=useRef<Draft|null>(null);
 const chapter=doc.chapters.find(c=>c.id===chapterId)||doc.chapters[0],count=doc.chapters.reduce((n,c)=>n+c.content.replace(/\s/g,'').length,0);
 const suggestions=doc.suggestions||[],versions=doc.versions||[],comparison=suggestions.find(s=>s.id===compareId);
 const activeSuggestions=suggestions.filter(s=>s.chapterId===chapter.id),activeVersions=versions.filter(v=>v.chapterId===chapter.id);
 function closeTour(){setTour(-1);try{localStorage.setItem('wenxu.tour.v3.'+identity.alias,'seen');}catch{}}
 function tourStep(n:number){const next=tourSteps[n].tab;setTab(next);setChaptersOpen(next==='chapters');setAssistantOpen(next==='prompt');setMode('edit');setAssistantTab('request');setTour(n);}
 function onImport(){closeTour();setChaptersOpen(false);setAssistantOpen(false);setImportOpen(true);}
 useEffect(()=>{document.title='文稿編輯器｜寫作工作區';},[]);
 useEffect(()=>{try{if(doc.chapters.some(c=>c.content.trim())||doc.title.trim())localStorage.setItem(draftKey(identity.alias),JSON.stringify(doc));else localStorage.removeItem(draftKey(identity.alias));setStatus('已存本機');}catch{setStatus('無法保存');setNotice('裝置儲存空間不足，請先匯出 Word。');}},[doc,identity.alias]);
 function remember(){setHistory(h=>[...h,doc].slice(-10));}
 function versionOf(c:PreviewChapter,reason:string){return {id:crypto.randomUUID(),chapterId:c.id,title:c.title,content:c.content,reason,createdAt:new Date().toISOString()};}
 function finishEdit(){const previous=beforeEdit.current;beforeEdit.current=null;if(previous&&previous!==doc){setHistory(h=>[...h,previous].slice(-10));const old=previous.chapters.find(c=>c.id===chapter.id);if(old&&old.content!==chapter.content)setDoc(d=>({...d,versions:[versionOf(old,'手動編輯前'),...(d.versions||[])].slice(0,30)}));}}
 function switchChapter(id:string){setChapterId(id);setSelection(null);setScope('chapter');setMode('edit');setTab('edit');setChaptersOpen(false);}
 function capture(){const e=editor.current;if(!e)return;const start=e.selectionStart,end=e.selectionEnd;if(start!==end){setSelection({start,end,text:chapter.content.slice(start,end)});setScope('selection');}else setSelection(null);}
 function suggestSelection(value:string){setPrompt(value);setScope('selection');setAssistantTab('request');setAssistantOpen(true);setChaptersOpen(false);setTab('prompt');}
 function openVersions(){setAssistantTab('versions');setAssistantOpen(true);setChaptersOpen(false);setTab('prompt');}
 function changeContent(content:string){setDoc(d=>({...d,chapters:d.chapters.map(c=>c.id===chapter.id?{...c,content}:c)}));setSelection(null);setStatus('保存中');}
 function format(kind:'bold'|'heading'|'list'|'quote'){const e=editor.current;if(!e)return;const start=e.selectionStart,end=e.selectionEnd,selected=chapter.content.slice(start,end)||'輸入文字';const value=kind==='bold'?'**'+selected+'**':selected.split('\n').map(line=>(kind==='heading'?'## ':kind==='list'?'- ':'> ')+line).join('\n');remember();changeContent(chapter.content.slice(0,start)+value+chapter.content.slice(end));requestAnimationFrame(()=>{e.focus();e.setSelectionRange(start,start+value.length);});}
 async function download(){setBusy(true);setNotice('');try{const project:Project={id:crypto.randomUUID(),title:doc.title||'文稿',documentType:'report',requirements:prompt,audience:'',sources:[],chapters:doc.chapters.map(c=>({...c,review:''})),revisions:[],version:1,updatedAt:new Date().toISOString()};await exportProject(project,'docx');setNotice('Word 已匯出，包含所有章節。');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 function undo(){const last=history.at(-1);if(!last)return;setDoc(last);setHistory(h=>h.slice(0,-1));setChapterId(last.chapters.some(c=>c.id===chapter.id)?chapter.id:last.chapters[0].id);setSelection(null);setMode('edit');setNotice('已復原上次修改。');}
 function snapshot(){setDoc(d=>({...d,versions:[versionOf(chapter,'手動保存版本'),...(d.versions||[])].slice(0,30)}));setNotice('目前章節已另存版本，可從版本時間軸還原。');openVersions();}
 function addChapter(){remember();const next={id:crypto.randomUUID(),title:'新章節 '+(doc.chapters.length+1),content:''};setDoc(d=>({...d,chapters:[...d.chapters,next]}));switchChapter(next.id);}
 function openManual(){if(!chapter.content.trim()){setNotice('請先匯入原稿或輸入正文。');return;}if(scope==='selection'&&!selection){setNotice('請先反白選取正文。');return;}setManualText('');setManualOpen(true);}
 function queueManual(){const next:Suggestion={id:crypto.randomUUID(),chapterId:chapter.id,original:chapter.content,replacement:manualText,selection:scope==='selection'&&selection?{start:selection.start,end:selection.end}:undefined,prompt:prompt||'外部修改建議',status:'pending',createdAt:new Date().toISOString()};setDoc(d=>({...d,suggestions:[next,...(d.suggestions||[])].slice(0,20)}));setManualOpen(false);setAssistantTab('suggestions');setAssistantOpen(true);setNotice('修改建議已加入，正文尚未改動。請先比較，再決定是否採用。');}
 function adopt(s:Suggestion){const result=resolveSuggestion(chapter,s);if(!result.ok){setNotice(result.error);return;}remember();setDoc(d=>({...d,chapters:d.chapters.map(c=>c.id===s.chapterId?{...c,content:result.content}:c),versions:[versionOf(chapter,'採用建議前'),...(d.versions||[])].slice(0,30),suggestions:(d.suggestions||[]).map(x=>x.id===s.id?{...x,status:'applied'}:x)}));setMode('edit');setSelection(null);setNotice('已採用修改建議，原正文保留在版本紀錄。');}
 function restore(v:SavedVersion){remember();setDoc(d=>({...d,chapters:d.chapters.map(c=>c.id===v.chapterId?{...c,title:v.title,content:v.content}:c),versions:[versionOf(chapter,'還原版本前'),...(d.versions||[])].slice(0,30)}));setMode('edit');setNotice('已還原章節版本，還原前的內容也已保存。');}
 return <div className="blue-preview product-workspace">
 <header className="bp-header">
 <a className="bp-brand" href="/" aria-label="文序首頁"><span className="bp-logo"><Feather size={21}/></span><span>文序</span></a>
 <span className="bp-header-divider"/><span className="bp-document-name">{doc.title||'未命名文稿'}</span>
 <span className="bp-local-label"><CheckCircle2 size={14}/>{status==='已存本機'?'僅儲存在這台裝置':status}</span>
 <div className="bp-header-actions">
 <button className="bp-guide-button" onClick={()=>tourStep(0)}><CircleHelp size={16}/>操作導覽</button>
 <button className="bp-import-action" data-tour="import" disabled={busy} onClick={onImport}><Upload size={16}/>匯入</button>
 <button className="bp-panel-action" aria-expanded={chaptersOpen} onClick={()=>{setChaptersOpen(v=>!v);setAssistantOpen(false);setTab('chapters');}}><BookOpen size={16}/>章節</button>
 <button className="bp-panel-action" aria-expanded={assistantOpen} onClick={()=>{setAssistantTab('request');setAssistantOpen(v=>!v);setChaptersOpen(false);setTab('prompt');}}><Sparkles size={16}/>修改工具</button>
 <button className="bp-primary" data-tour="export" disabled={busy||!count} onClick={()=>void download()}><Download size={16}/>匯出 Word</button>
 <span className="bp-account"><span className="bp-avatar">{identity.alias.slice(0,1).toUpperCase()}</span>{identity.alias}</span><button className="bp-logout" onClick={onLogout}>登出</button>
 </div></header>
 <main className="bp-main"><nav className="bp-mobile-tabs" aria-label="工作區切換">{[['chapters','章節'],['edit','編輯'],['prompt','修改要求']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>{notice&&<div className="bp-notice" role="status"><CheckCircle2 size={15}/><span>{notice}</span><button aria-label="關閉訊息" onClick={()=>setNotice('')}><X size={15}/></button></div>}
 <div className={'bp-workspace bp-tab-'+tab+(chaptersOpen?' bp-show-chapters':'')+(assistantOpen?' bp-show-assistant':'')}>
 <nav className="bp-icon-rail" aria-label="工作區導覽">
 <button aria-label="章節導覽" title="章節導覽" aria-expanded={chaptersOpen} onClick={()=>{setChaptersOpen(v=>!v);setAssistantOpen(false);}}><BookOpen size={19}/></button>
 <button aria-label="匯入原稿" title="匯入原稿" onClick={onImport}><Upload size={19}/></button>
 <button aria-label="修改要求" title="修改要求" aria-expanded={assistantOpen&&assistantTab==='request'} onClick={()=>{setAssistantTab('request');setAssistantOpen(true);setChaptersOpen(false);}}><Sparkles size={19}/></button>
 <button aria-label="版本時間軸" title="版本時間軸" onClick={openVersions}><History size={19}/></button>
 </nav>
 {(chaptersOpen||assistantOpen)&&<button className="bp-panel-scrim" aria-label="關閉側邊面板" onClick={()=>{setChaptersOpen(false);setAssistantOpen(false);}}/>}
 <aside className="bp-chapters" aria-label="章節清單"><div className="bp-drawer-head"><strong>章節導覽</strong><button aria-label="關閉章節導覽" onClick={()=>{setChaptersOpen(false);setTab('edit');}}><X size={17}/></button></div><div className="bp-project-label">目前文稿</div><div className="bp-project-title"><BookOpen size={17}/><strong>{doc.title||'未命名文稿'}</strong></div><div className="bp-source-box"><span><FileText size={15}/>{doc.sourceName?'已匯入原稿':'原稿來源'}</span><p>{doc.sourceName||'加入書籍或專案文本，開始逐章修改。'}</p><button onClick={onImport}>{doc.sourceName?'更換原稿':'匯入或貼上文字'}<ArrowRight size={13}/></button></div>
 <div className="bp-nav-heading"><h2>章節</h2><span>{doc.chapters.length}</span><button aria-label="新增章節" title="新增章節" disabled={doc.chapters.length>=40} onClick={addChapter}><Plus size={16}/></button></div>
 <div className="bp-chapter-list" data-tour="chapters">{doc.chapters.map((c,i)=><button key={c.id} aria-current={c.id===chapter.id?'page':undefined} onClick={()=>switchChapter(c.id)}><span className="bp-chapter-number">{String(i+1).padStart(2,'0')}</span><span className="bp-chapter-text"><strong>{c.title}</strong><small>{c.content.replace(/\s/g,'').length.toLocaleString()} 字</small></span></button>)}</div>
 <div className="bp-nav-bottom"><span><CheckCircle2 size={13}/>{status}</span><p>{count.toLocaleString()} 字 · {doc.chapters.length} 章<br/>草稿僅保存於這個瀏覽器</p></div></aside>
 <section className="bp-paper" aria-label="正文編輯"><div className="bp-paper-toolbar"><div className="bp-breadcrumb"><FileText size={14}/><select aria-label="目前章節" value={chapter.id} onChange={e=>switchChapter(e.target.value)}>{doc.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><span className="bp-editor-status"><CheckCircle2 size={12}/>{status}</span></div>
 <div className="bp-formatbar"><div className="bp-mode-tabs"><button aria-pressed={mode==='edit'} onClick={()=>setMode('edit')}>編輯</button><button aria-pressed={mode==='preview'} onClick={()=>setMode('preview')}>預覽</button></div><span className="bp-toolbar-separator"/>{mode==='edit'&&<><button aria-label="粗體" title="粗體" onMouseDown={e=>e.preventDefault()} onClick={()=>format('bold')}><Bold size={16}/></button><button aria-label="小標題" title="小標題" onMouseDown={e=>e.preventDefault()} onClick={()=>format('heading')}><Heading2 size={18}/></button><button aria-label="項目清單" title="項目清單" onMouseDown={e=>e.preventDefault()} onClick={()=>format('list')}><List size={17}/></button><button aria-label="引用段落" title="引用段落" onMouseDown={e=>e.preventDefault()} onClick={()=>format('quote')}><Quote size={15}/></button></>}<div className="bp-format-end"><button aria-label="復原上次修改" title="復原上次修改" disabled={!history.length} onClick={undo}><Undo2 size={16}/></button><button aria-label="保存章節版本" title="保存章節版本" disabled={!chapter.content.trim()} onClick={snapshot}><History size={16}/></button></div></div>
 <div className="bp-canvas"><article className="bp-document"><div className="bp-document-meta"><span>文稿 / {String(doc.chapters.findIndex(c=>c.id===chapter.id)+1).padStart(2,'0')}</span><span>{chapter.content.replace(/\s/g,'').length} 字</span></div>{mode==='edit'?<><label className="bp-edit-label" htmlFor="bp-title">文稿標題</label><input id="bp-title" className="bp-doc-title" aria-label="文稿標題" maxLength={160} placeholder="為這份文稿命名" value={doc.title} onFocus={()=>{beforeEdit.current=doc;}} onChange={e=>setDoc(d=>({...d,title:e.target.value}))} onBlur={finishEdit}/>
 <label className="bp-edit-label bp-chapter-edit-label" htmlFor="bp-chapter-title">目前章節名稱</label><input id="bp-chapter-title" className="bp-chapter-title-input" aria-label="章節標題" value={chapter.title} maxLength={160} onFocus={()=>{beforeEdit.current=doc;}} onChange={e=>setDoc(d=>({...d,chapters:d.chapters.map(c=>c.id===chapter.id?{...c,title:e.target.value}:c)}))} onBlur={finishEdit}/>
 </>:<><h1 className="bp-reading-title">{doc.title||'未命名文稿'}</h1><h2 className="bp-reading-section">{chapter.title}</h2></>}
{mode==='edit'?<>{selection&&<div className="bp-selection-toolbar" role="group" aria-label="針對反白文字修改"><span>已選取 {selection.text.length} 字</span><button onMouseDown={e=>e.preventDefault()} onClick={()=>suggestSelection('精簡選取文字，保留原意及關鍵事實。')}>精簡</button><button onMouseDown={e=>e.preventDefault()} onClick={()=>suggestSelection('保留原意，將選取文字改為正式且流暢的語氣。')}>正式語氣</button><button onMouseDown={e=>e.preventDefault()} onClick={()=>suggestSelection('潤飾選取文字的表達，保留原有事實與引用。')}>潤飾</button><button className="bp-selection-custom" onMouseDown={e=>e.preventDefault()} onClick={()=>suggestSelection('')}>自訂修改 <ArrowRight size={14}/></button></div>}<label className="bp-edit-label bp-body-label" htmlFor="bp-body"><PencilLine size={12}/>正文 · 可直接編輯，反白文字可指定修改範圍</label><textarea id="bp-body" data-tour="body" ref={editor} aria-label="正文內容" spellCheck={false} value={chapter.content} placeholder="先匯入原稿，或在這裡開始寫作。\n\n上方工具列可加入小標題、粗體、清單與引用。" onFocus={()=>{beforeEdit.current=doc;}} onChange={e=>changeContent(e.target.value)} onSelect={capture} onBlur={finishEdit} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='b'){e.preventDefault();format('bold');}}}/><span className="bp-markdown-note">工具列使用 Markdown 排版，可切到「預覽」查看成稿。</span></>:mode==='compare'&&comparison?<div className="bp-comparison"><header><div><h3>逐段修改比較</h3><p>紅色為移除、綠色為新增。請確認後再採用。</p></div><button onClick={()=>setMode('edit')}>返回編輯</button></header><DiffView before={comparison.selection?comparison.original.slice(comparison.selection.start,comparison.selection.end):comparison.original} after={comparison.replacement}/>{comparison.status==='pending'&&<button className="bp-primary" onClick={()=>adopt(comparison)}>採用這份建議 <Check size={15}/></button>}</div>:<div className="bp-rendered"><Markdown>{chapter.content||'尚未加入正文。請回到編輯，匯入原稿或開始寫作。'}</Markdown></div>}
 </article></div><footer className="bp-paper-footer"><span>{mode==='preview'?'成稿預覽':mode==='compare'?'比較後再採用，原稿會保留版本':'正在編輯：'+chapter.title}</span><span>{selection?('已選取 '+selection.text.length+' 字'):('全文 '+count.toLocaleString()+' 字')}</span></footer></section>
 <aside className="bp-assistant" aria-label="修改工具"><header className="bp-assistant-header"><span className="bp-assistant-icon"><Sparkles size={17}/></span><div><h2>寫作助手</h2><span>針對原稿，逐段修改</span></div><span className="bp-offline"><span/>AI 未連線</span><button className="bp-drawer-close" aria-label="關閉修改工具" onClick={()=>{setAssistantOpen(false);setTab('edit');}}><X size={17}/></button></header>
 <nav className="bp-assistant-tabs" aria-label="助手功能">{[['request','修改要求'],['suggestions','建議'],['versions','版本']].map(([id,label])=><button key={id} aria-pressed={assistantTab===id} onClick={()=>setAssistantTab(id)}>{label}{id==='suggestions'&&activeSuggestions.length>0&&<small>{activeSuggestions.length}</small>}{id==='versions'&&activeVersions.length>0&&<small>{activeVersions.length}</small>}</button>)}</nav>
 <div className="bp-assistant-content">{assistantTab==='request'?<><div className="bp-target-context"><span>本次修改對象</span><strong><FileText size={14}/>{chapter.title}</strong><div className="bp-scope"><button aria-pressed={scope==='chapter'} onClick={()=>setScope('chapter')}>整個章節</button><button aria-pressed={scope==='selection'} onClick={()=>setScope('selection')}>反白段落</button></div>{scope==='selection'&&<p>{selection?'已選取 '+selection.text.length+' 字':'請先在正文反白需要修改的段落。'}</p>}</div>
 <label className="bp-field-label" htmlFor="bp-prompt">你希望怎麼修改？</label><textarea id="bp-prompt" data-tour="prompt" aria-label="提示詞" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="例如：保留原意與引用，改成正式計畫書語氣，精簡重複的敘述。"/><span className="bp-input-hint">保留原有事實，缺少資料時標記待補充。</span>
 <div className="bp-presets"><span>快速填入</span><button onClick={()=>setPrompt('保留原意、資料與引用，改成正式計畫書語氣，不新增未提供的事實。')}>正式語氣</button><button onClick={()=>setPrompt('精簡重複敘述，保留關鍵資料、數字與引用，不新增未提供的事實。')}>精簡內容</button><button onClick={()=>setPrompt('保留原意與引用，調整段落順序並補上小標題，缺少資料標記待補充。')}>整理段落</button></div>
 <button className="bp-primary bp-execute" onClick={()=>setNotice(!prompt.trim()?'請先寫下修改要求。':scope==='selection'&&!selection?'請先在正文反白選取文字。':'AI 尚未連線，這次沒有修改正文。可先貼上外部修改建議，試用比較與採用。')}>產生修改建議<ArrowRight size={16}/></button><div className="bp-ai-state"><CircleHelp size={15}/><p>AI 尚未連線。你仍可手動編輯，或貼上已有建議，先體驗比較與採用。</p></div>
 <div className="bp-manual-entry"><h3>已經有修改建議？</h3><p>把老師、自己或其他工具的建議貼進來，先比較，再採用。</p><button onClick={openManual}><ClipboardPaste size={15}/>貼上修改建議</button></div></>:assistantTab==='suggestions'?<><div className="bp-panel-caption">「{chapter.title}」的修改建議</div>{activeSuggestions.length?activeSuggestions.map(s=><article className="bp-suggestion" key={s.id}><header><span><ClipboardPaste size={13}/>使用者貼上</span><small>{s.status==='pending'?'等待採用':s.status==='applied'?'已採用':'已略過'}</small></header><h3>{s.prompt}</h3><p>{s.replacement.slice(0,240)}{s.replacement.length>240?'…':''}</p><div><button onClick={()=>{setCompareId(s.id);setMode('compare');setTab('edit');}}>比較原稿</button>{s.status==='pending'&&<><button className="bp-primary" onClick={()=>adopt(s)}>採用</button><button aria-label="略過這份建議" onClick={()=>setDoc(d=>({...d,suggestions:(d.suggestions||[]).map(x=>x.id===s.id?{...x,status:'dismissed'}:x)}))}>略過</button></>}</div></article>):<div className="bp-assistant-empty"><MessagesSquare size={29}/><h3>建議會出現在這裡</h3><p>修改結果先保留在這裡，確認後才更新正文。</p><button onClick={openManual}>貼上修改建議</button></div>}</>:<><div className="bp-panel-caption">目前章節的保存版本</div><button className="bp-save-version" disabled={!chapter.content.trim()} onClick={snapshot}><Plus size={14}/>保存目前版本</button>{activeVersions.length?activeVersions.map(v=><article className="bp-version" key={v.id}><header><History size={14}/><strong>{v.reason}</strong></header><span>{new Date(v.createdAt).toLocaleString('zh-TW',{hour12:false})}</span><p>{v.content.slice(0,85)||'空白正文'}{v.content.length>85?'…':''}</p><button onClick={()=>restore(v)}>還原此版本</button></article>):<div className="bp-assistant-empty"><History size={29}/><h3>保留每次重要修改</h3><p>採用建議前會保存原正文，也可以手動保存版本。</p></div>}</>}</div>
 <footer className="bp-assistant-footer"><ShieldCheck size={13}/>修改建議需由你確認，不會直接覆寫原稿。</footer></aside></div></main>
 {importOpen&&<ImportDialog onClose={()=>setImportOpen(false)} onConfirm={next=>{remember();setDoc({...next,sourceName:next.title,versions:[...doc.chapters.map(c=>versionOf(c,'匯入其他原稿前')),...versions].slice(0,30)});switchChapter(next.chapters[0].id);setImportOpen(false);setNotice('原稿已加入，可以從左欄選擇章節。');}}/>}
 {manualOpen&&<div className="bp-modal-backdrop"><section className="bp-manual-dialog" onKeyDown={e=>{if(e.key==="Escape")setManualOpen(false);if(e.key==="Tab"){const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>("button:not(:disabled),textarea"));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} role="dialog" aria-modal="true" aria-labelledby="bp-manual-heading"><header><h2 id="bp-manual-heading">貼上修改建議</h2><button aria-label="關閉修改建議" onClick={()=>setManualOpen(false)}><X size={18}/></button></header><p>對象：{chapter.title} · {scope==='selection'?'反白段落':'整個章節'}。請貼上建議改寫後的完整文字。</p><label htmlFor="bp-manual-text">修改後文字</label><textarea id="bp-manual-text" autoFocus value={manualText} onChange={e=>setManualText(e.target.value)}/><span>這是你提供的內容，不是本網站的 AI 生成結果。</span><footer><button onClick={()=>setManualOpen(false)}>取消</button><button className="bp-primary" disabled={!manualText.trim()||new TextEncoder().encode(manualText).length>1800000} onClick={queueManual}>加入待確認建議<ArrowRight size={15}/></button></footer></section></div>}
 {tour>=0&&!importOpen&&!manualOpen&&<WorkspaceTour step={tour} onStep={tourStep} onClose={closeTour}/>}
 </div>;
}
function DiffView({before,after}:{before:string;after:string}){
 let prefix=0;while(prefix<before.length&&prefix<after.length&&before[prefix]===after[prefix])prefix++;
 let suffix=0;while(suffix<before.length-prefix&&suffix<after.length-prefix&&before[before.length-1-suffix]===after[after.length-1-suffix])suffix++;
 const removed=before.slice(prefix,before.length-suffix),added=after.slice(prefix,after.length-suffix);
 return <div className="bp-diff-text" aria-label="原稿與建議的文字差異"><span>{before.slice(0,prefix)}</span>{removed&&<del>{removed}</del>}{added&&<ins>{added}</ins>}<span>{suffix?before.slice(before.length-suffix):''}</span>{!removed&&!added&&<p>這份建議與原文相同。</p>}</div>;
}
function Markdown({children}:{children:string}){return <ReactMarkdown remarkPlugins={[remarkGfm]}>{children}</ReactMarkdown>;}

function ImportDialog({onClose,onConfirm}:{onClose:()=>void;onConfirm:(d:Draft)=>void}){
 const [text,setText]=useState(''),[title,setTitle]=useState('匯入文稿'),[chapters,setChapters]=useState<PreviewChapter[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const file=useRef<HTMLInputElement>(null),panel=useRef<HTMLElement>(null),previous=useRef(document.activeElement as HTMLElement|null);
 useEffect(()=>{panel.current?.focus();return()=>{previous.current?.focus();};},[]);
 function prepare(value:string,name:string){const parts=splitImportedText(value);if(!parts.length)throw new Error('沒有可讀取文字；掃描 PDF 需要先轉成文字。');if(parts.length>40||new TextEncoder().encode(value).length>1800000)throw new Error('支援最多40章、1.8MB文字，請先分段匯入。');setText(value);setTitle(name);setChapters(parts);setError('');}
 async function read(f:File){setBusy(true);setError('');try{prepare(await extractSource(f),f.name.replace(/\.[^.]+$/,''));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="bp-modal-backdrop"><section ref={panel} tabIndex={-1} className="bp-import-dialog" role="dialog" aria-modal="true" aria-labelledby="bp-import-heading" onKeyDown={e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const items=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not([hidden]),textarea')||[]);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
 <header><div><h2 id="bp-import-heading">匯入原稿</h2><p>選檔或貼上文字，確認內容後再加入工作區。</p></div><button aria-label="關閉匯入" disabled={busy} onClick={onClose}><X size={18}/></button></header>
 <div className="bp-import-steps" aria-label="匯入步驟"><span><b>1</b> 上傳原稿</span><span><b>2</b> 檢查章節</span><span><b>3</b> 確認匯入</span></div><div className="bp-guide-grid"><section className="bp-import-panel"><button className="bp-file-pick" disabled={busy} onClick={()=>file.current?.click()}><Upload size={25}/><strong>{busy?'讀取中…':'選擇原稿檔案'}</strong><span>Word · 含文字 PDF · TXT · Markdown</span></button><label className="bp-field-label" htmlFor="bp-source">或在藍色區域貼上原稿</label><textarea id="bp-source" value={text} onChange={e=>{setText(e.target.value);setChapters([]);}} placeholder="貼上原書籍或專案文本。章節可用「第一章」或 Markdown 標題。"/><button disabled={busy||!text.trim()} onClick={()=>{try{prepare(text,title);}catch(e){setError((e as Error).message);}}}>預覽文字與章節<ArrowRight size={16}/></button><p className="bp-limit">原始檔保留在裝置。不支援掃描PDF、OCR與圖片；匯出會重新排版。</p><button className="bp-sample-link" disabled={busy} onClick={()=>prepare(SAMPLE,'社區閱讀推廣計畫')}>使用示範原稿</button></section>
 <section className="bp-detected-chapters"><h3>辨識章節 <span>{chapters.length||'—'}</span></h3>{chapters.length?<div className="bp-import-chapter-list">{chapters.map((c,i)=><div key={c.id}><b>{String(i+1).padStart(2,'0')}</b><span>{c.title}</span></div>)}</div>:<p>選擇檔案或貼上文字後，將自動辨識章節。</p>}</section><section className="bp-source-preview"><h3>內容預覽</h3>{chapters.length?<><label className="bp-field-label" htmlFor="bp-new-title">文稿名稱</label><input id="bp-new-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/><p>辨識到 {chapters.length} 個章節，請確認文字正確。</p><div className="bp-source-scroll">{chapters.map(c=><article key={c.id}><h3>{c.title}</h3><p>{c.content}</p></article>)}</div></>:<div className="bp-preview-empty"><FileText size={30}/><p>讀取原稿後，文字與章節會顯示在這裡。</p></div>}</section></div>
 {error&&<p className="bp-error" role="alert">{error}</p>}<footer><span>確認後會取代目前草稿；可用「復原」還原。</span><button onClick={onClose} disabled={busy}>取消</button><button className="bp-primary" disabled={!chapters.length||busy} onClick={()=>onConfirm({title:title||'未命名文稿',chapters})}>確認匯入<ArrowRight size={16}/></button></footer>
 <input ref={file} type="file" hidden accept=".docx,.pdf,.txt,.md" onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.target.value='';}}/></section></div>;
}

export default function BluePreview(){
 const [identity,setIdentity]=useState<Identity|null>(null),[checking,setChecking]=useState(true),[alias,setAlias]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Draft|null>(null);
 function acceptIdentity(who:Identity){setExpectedAlias(who.alias);setIdentity(who);setDraft(initial(who.alias)||{title:'',chapters:[{id:crypto.randomUUID(),title:'開始寫作',content:''}]});setPassword('');}
 useEffect(()=>{let active=true;void api<Identity>('/me').then(who=>{if(active)acceptIdentity(who);}).catch(()=>{}).finally(()=>{if(active)setChecking(false);});return()=>{active=false;};},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{acceptIdentity(await api<Identity>('/login','POST',{alias,password}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await api('/logout','POST');setExpectedAlias(null);setIdentity(null);setDraft(null);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(checking)return <div className="blue-preview bp-entry"><p role="status">正在確認登入狀態…</p></div>;
 if(!identity)return <div className="blue-preview bp-entry">
 <header className="bp-login-brand"><span className="bp-logo"><Feather size={25}/></span><strong>文序</strong><span>書寫，讓思緒更清晰</span></header>
 <div className="bp-login-layout">
 <form className="bp-login-form" onSubmit={e=>void login(e)}>
 <h1>歡迎回到文序</h1><p>繼續編輯，讓思緒走得更遠。</p>
 <label htmlFor="bp-alias">使用者代號</label><input id="bp-alias" autoComplete="username" required value={alias} onChange={e=>setAlias(e.target.value)} placeholder="請輸入使用者代號"/>
 <label htmlFor="bp-password">密碼</label><input id="bp-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="請輸入密碼"/>
 {error&&<p className="bp-error" role="alert">{error}</p>}
 <button className="bp-primary" disabled={busy} type="submit">{busy?'登入中…':'登入'}<ArrowRight size={17}/></button>
 {['127.0.0.1','localhost','[::1]'].includes(location.hostname)&&<div className="bp-demo">僅供本機測試 · 帳號 <b>demo</b> · 密碼 <b>local-demo-only</b></div>}
 <div className="bp-login-privacy"><ShieldCheck size={19}/><div><strong>草稿儲存在這台裝置</strong><span>目前尚未啟用雲端同步或 AI 修改。請定期匯出 Word 備份。</span></div></div>
 </form></div></div>;
 return draft&&identity?<Workspace key={identity.alias} identity={identity} seed={draft} onLogout={()=>void logout()}/>:null;
}
