import JSZip from 'jszip';
import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, ExternalHyperlink } from 'docx';
import type { Project } from './types';
import type { TDocumentDefinitions } from 'pdfmake/interfaces';

type Block={kind:'heading'|'paragraph'|'quote'|'list'|'code'|'table';text:string;level?:number;rows?:string[][];ordered?:boolean};
type Inline={text:string;bold?:boolean;code?:boolean;url?:string};
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const safeUrl=(s:string)=>/^(https?:|mailto:)/i.test(s)?s:'';
function inline(s:string):Inline[]{const out:Inline[]=[];const re=/\*\*([^*]+)\*\*|`([^`]+)`|\[([^\]]+)\]\(([^)]+)\)/g;let start=0;for(const m of s.matchAll(re)){if(m.index!>start)out.push({text:s.slice(start,m.index)});out.push(m[1]?{text:m[1],bold:true}:m[2]?{text:m[2],code:true}:{text:m[3],url:safeUrl(m[4])});start=m.index!+m[0].length;}if(start<s.length)out.push({text:s.slice(start)});return out;}
function blocks(markdown:string):Block[]{const lines=markdown.replace(/\r/g,'').split('\n');const out:Block[]=[];const cell=(l:string)=>l.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(v=>v.trim());for(let i=0;i<lines.length;i++){let s=lines[i];if(!s.trim())continue;if(/^```/.test(s)){const code:string[]=[];while(++i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i]);out.push({kind:'code',text:code.join('\n')});continue;}if(s.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-{3,}/.test(lines[i+1])){const rows=[cell(s)];i++;while(i+1<lines.length&&lines[i+1].includes('|'))rows.push(cell(lines[++i]));out.push({kind:'table',text:'',rows});continue;}const h=s.match(/^(#{1,6})\s+(.+)$/);if(h){out.push({kind:'heading',text:h[2],level:h[1].length});continue;}const list=s.match(/^\s*(?:([-*+])|(\d+)\.)\s+(.+)$/);if(list){out.push({kind:'list',text:list[3],ordered:!!list[2]});continue;}if(/^>\s?/.test(s)){out.push({kind:'quote',text:s.replace(/^>\s?/,'')});continue;}while(i+1<lines.length&&lines[i+1].trim()&&!/^(#|>|```|\s*[-*+]\s|\s*\d+\.\s)/.test(lines[i+1]))s+='\n'+lines[++i];out.push({kind:'paragraph',text:s});}return out;}
const SOURCE_NOTICE='來源由使用者提供；未進行外部事實查核。';
function withSourceIndex(project:Project):Project{return {...project,chapters:[...project.chapters,{id:'export-source-index',title:'來源對照',content:SOURCE_NOTICE+'\n\n'+(project.sources.length?project.sources.map(source=>`- [S-${source.id}] ${source.name.replace(/[\r\n]/g,' ')}`).join('\n'):'本文件尚未加入來源。'),review:''}]};}
export function buildMarkdown(project:Project):string{project=withSourceIndex(project);return `# ${project.title}\n\n`+project.chapters.map(c=>`## ${c.title}\n\n${c.content}`).join('\n\n');}
const docRuns=(text:string)=>inline(text).map(r=>r.url?new ExternalHyperlink({link:r.url,children:[new TextRun({text:r.text,style:'Hyperlink'})]}):new TextRun({text:r.text,bold:r.bold,font:r.code?'Consolas':undefined}));
export async function buildDocx(project:Project):Promise<Uint8Array>{project=withSourceIndex(project);const children:(Paragraph|Table)[]=[new Paragraph({text:project.title,heading:HeadingLevel.TITLE})];for(const chapter of project.chapters){children.push(new Paragraph({text:chapter.title,heading:HeadingLevel.HEADING_1,pageBreakBefore:children.length>1}));for(const b of blocks(chapter.content)){if(b.kind==='table'){children.push(new Table({rows:b.rows!.map((row,index)=>new TableRow({children:row.map(value=>new TableCell({children:[new Paragraph({children:docRuns(value)})]})),tableHeader:index===0}))}));continue;}children.push(new Paragraph({children:docRuns(b.text),heading:b.kind==='heading'?([HeadingLevel.HEADING_2,HeadingLevel.HEADING_3,HeadingLevel.HEADING_4,HeadingLevel.HEADING_5,HeadingLevel.HEADING_6][Math.min((b.level??1)-1,4)]):undefined,bullet:b.kind==='list'&&!b.ordered?{level:0}:undefined,numbering:b.kind==='list'&&b.ordered?{reference:'numbers',level:0}:undefined,indent:b.kind==='quote'?{left:400}:undefined,shading:b.kind==='code'?{fill:'F3F4F6'}:undefined,spacing:{after:160}}));}}const doc=new Document({title:project.title,creator:'通用文書工作台',numbering:{config:[{reference:'numbers',levels:[{level:0,format:'decimal',text:'%1.',alignment:'left'}]}]},styles:{default:{document:{run:{font:'Noto Sans TC',size:22}}}},sections:[{children}]});return new Uint8Array(await Packer.toArrayBuffer(doc));}
function inlineHtml(text:string):string{return inline(text).map(r=>r.url?`<a href="${esc(r.url)}">${esc(r.text)}</a>`:r.bold?`<strong>${esc(r.text)}</strong>`:r.code?`<code>${esc(r.text)}</code>`:esc(r.text).replace(/\n/g,'<br/>')).join('');}
function bodyHtml(content:string):string{return blocks(content).map(b=>{if(b.kind==='table')return '<table>'+b.rows!.map((r,i)=>'<tr>'+r.map(c=>`<${i?'td':'th'}>${inlineHtml(c)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table>';if(b.kind==='code')return `<pre><code>${esc(b.text)}</code></pre>`;if(b.kind==='heading'){const h=Math.min((b.level??1)+1,6);return `<h${h}>${inlineHtml(b.text)}</h${h}>`;}if(b.kind==='list')return `<${b.ordered?'ol':'ul'}><li>${inlineHtml(b.text)}</li></${b.ordered?'ol':'ul'}>`;return `<${b.kind==='quote'?'blockquote':'p'}>${inlineHtml(b.text)}</${b.kind==='quote'?'blockquote':'p'}>`;}).join('\n');}
export async function buildEpub(project:Project):Promise<Uint8Array>{project=withSourceIndex(project);const zip=new JSZip();zip.file('mimetype','application/epub+zip',{compression:'STORE'});zip.file('META-INF/container.xml','<?xml version="1.0" encoding="UTF-8"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>');const items=project.chapters.map((_,i)=>`<item id="chapter${i+1}" href="chapter-${i+1}.xhtml" media-type="application/xhtml+xml"/>`).join('');const spine=project.chapters.map((_,i)=>`<itemref idref="chapter${i+1}"/>`).join('');zip.file('OEBPS/content.opf',`<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">urn:uuid:${esc(project.id)}</dc:identifier><dc:title>${esc(project.title)}</dc:title><dc:language>zh-TW</dc:language><meta property="dcterms:modified">${new Date(project.updatedAt).toISOString().replace(/\.\d+Z$/,'Z')}</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>${items}</manifest><spine>${spine}</spine></package>`);zip.file('OEBPS/nav.xhtml',`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="zh-TW"><head><title>目錄</title></head><body><nav epub:type="toc"><h1>${esc(project.title)}</h1><ol>${project.chapters.map((c,i)=>`<li><a href="chapter-${i+1}.xhtml">${esc(c.title)}</a></li>`).join('')}</ol></nav></body></html>`);project.chapters.forEach((c,i)=>zip.file(`OEBPS/chapter-${i+1}.xhtml`,`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" lang="zh-TW"><head><title>${esc(c.title)}</title><style>body{line-height:1.7}table{border-collapse:collapse}td,th{border:1px solid;padding:0.3em}pre{white-space:pre-wrap}blockquote{border-left:3px solid #888;padding-left:1em}</style></head><body><h1>${esc(c.title)}</h1>${bodyHtml(c.content)}</body></html>`));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
export function buildPdfDefinition(project:Project):TDocumentDefinitions{project=withSourceIndex(project);const content:any[]=[{text:project.title,fontSize:24,margin:[0,0,0,24]}];const rich=(s:string)=>inline(s).map(r=>({text:r.text,bold:r.bold,link:r.url,color:r.url?'#1769aa':undefined}));for(const c of project.chapters){content.push({text:c.title,fontSize:20,margin:[0,14,0,14]});for(const b of blocks(c.content)){if(b.kind==='table'){const width=Math.max(...b.rows!.map(r=>r.length));content.push({table:{headerRows:1,widths:Array(width).fill('*'),body:b.rows!.map(r=>Array.from({length:width},(_,i)=>({text:rich(r[i]??'')})))},margin:[0,8,0,12]});}else content.push({text:rich((b.kind==='list'?(b.ordered?'1. ':'• '):'')+b.text),fontSize:b.kind==='heading'?16:11,margin:b.kind==='quote'?[18,4,0,10]:[0,4,0,10],background:b.kind==='code'?'#f3f4f6':undefined});}}return {info:{title:project.title},defaultStyle:{font:'NotoSansTC',lineHeight:1.35},pageMargins:[44,48,44,48],content};}
export async function buildPdf(project:Project):Promise<Blob>{const mod=await import('pdfmake/build/pdfmake');const pdfMake=mod.default as typeof mod.default & {addVirtualFileSystem(vfs:Record<string,string>):void;addFonts(fonts:Record<string,{normal:string;bold:string;italics:string;bolditalics:string}>):void};const response=await fetch(`${import.meta.env.BASE_URL}fonts/NotoSansTC-Regular.otf`);if(!response.ok)throw new Error('繁中字型載入失敗，請確認字型檔存在。');const buffer=await response.arrayBuffer();let binary='';const bytes=new Uint8Array(buffer);for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const boldResponse=await fetch(import.meta.env.BASE_URL+'fonts/NotoSansTC-Bold.otf');if(!boldResponse.ok)throw new Error('繁中粗體字型載入失敗。');const boldBytes=new Uint8Array(await boldResponse.arrayBuffer());let boldBinary='';for(let i=0;i<boldBytes.length;i+=8192)boldBinary+=String.fromCharCode(...boldBytes.subarray(i,i+8192));pdfMake.addVirtualFileSystem({'NotoSansTC-Regular.otf':btoa(binary),'NotoSansTC-Bold.otf':btoa(boldBinary)});pdfMake.addFonts({NotoSansTC:{normal:'NotoSansTC-Regular.otf',bold:'NotoSansTC-Bold.otf',italics:'NotoSansTC-Regular.otf',bolditalics:'NotoSansTC-Bold.otf'}});return new Promise((resolve,reject)=>{try{pdfMake.createPdf(buildPdfDefinition(project)).getBlob(resolve);}catch(e){reject(e);}});}
export async function extractSource(file:File):Promise<string>{if(file.size>10*1024*1024)throw new Error('每個來源檔案上限為 10 MB。');const ext=file.name.split('.').pop()?.toLowerCase();if(!['txt','md','docx','pdf'].includes(ext??''))throw new Error('只支援 TXT、MD、DOCX 與含文字的 PDF。');if(ext==='txt'||ext==='md')return (await file.text()).replace(/^\uFEFF/,'');const buffer=await file.arrayBuffer();if(ext==='docx'){const mammoth=await import('mammoth/mammoth.browser');const result=await mammoth.extractRawText({arrayBuffer:buffer});if(!result.value.trim())throw new Error('DOCX 沒有可讀取文字；圖片與公式不支援匯入。');return result.value;}const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl;const loading=pdfjs.getDocument({data:new Uint8Array(buffer)});const doc=await loading.promise;try{const pages:string[]=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n);const text=await page.getTextContent();pages.push(text.items.map(item=>'str' in item?item.str+('hasEOL' in item&&item.hasEOL?'\n':' '):'').join(''));}const result=pages.join('\n\n').trim();if(!result)throw new Error('PDF 沒有可讀取文字，可能為掃描檔；請先進行 OCR。');return result;}finally{await loading.destroy();}}
export async function exportProject(project:Project,format:'md'|'docx'|'pdf'|'epub'):Promise<void>{if(!project.chapters.length)throw new Error('請先建立至少一個章節。');let blob:Blob;if(format==='md')blob=new Blob([buildMarkdown(project)],{type:'text/markdown;charset=utf-8'});else if(format==='pdf')blob=await buildPdf(project);else {const bytes=format==='docx'?await buildDocx(project):await buildEpub(project);blob=new Blob([bytes as BlobPart],{type:format==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/epub+zip'});}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${project.title.replace(/[<>:"/\\|?*\u0000-\u001F]/g,'_')||'文件'}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}





